#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XAppP001.Resource", IsApplication=true)]

namespace XAppP001
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int tvResult = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int tvResult = 2131034112;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calculator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int display = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int DisplayMetrics = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int quit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int reset = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int setting2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int settings = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080018
			public const int btnAdd = 2131230744;
			
			// aapt resource value: 0x7f080022
			public const int btnCancel = 2131230754;
			
			// aapt resource value: 0x7f08001b
			public const int btnDiv = 2131230747;
			
			// aapt resource value: 0x7f08001a
			public const int btnMult = 2131230746;
			
			// aapt resource value: 0x7f080021
			public const int btnSave = 2131230753;
			
			// aapt resource value: 0x7f080019
			public const int btnSub = 2131230745;
			
			// aapt resource value: 0x7f08001e
			public const int etDefaultNum1 = 2131230750;
			
			// aapt resource value: 0x7f080020
			public const int etDefaultNum2 = 2131230752;
			
			// aapt resource value: 0x7f080016
			public const int etNum1 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int etNum2 = 2131230743;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout2 = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int linearLayout3 = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout4 = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout5 = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int linearLayout6 = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout7 = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int linearLayout8 = 2131230739;
			
			// aapt resource value: 0x7f080023
			public const int mgrpCalculator = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int mgrpGeneral = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int miCalculator = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int miDisplayMetrics = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int miPreferences = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int miQuit = 2131230761;
			
			// aapt resource value: 0x7f080024
			public const int miReset = 2131230756;
			
			// aapt resource value: 0x7f08001d
			public const int tvDefaultCalcNum1Label = 2131230749;
			
			// aapt resource value: 0x7f08001f
			public const int tvDefaultCalcNum2Label = 2131230751;
			
			// aapt resource value: 0x7f080005
			public const int tvDensityDpiLabel = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int tvDensityDpiValue = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int tvDensityLabel = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int tvDensityValue = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int tvHeightPixelsLabel = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int tvHeightPixelsValue = 2131230732;
			
			// aapt resource value: 0x7f08001c
			public const int tvResult = 2131230748;
			
			// aapt resource value: 0x7f080008
			public const int tvScaledDensityLabel = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int tvScaledDensityValue = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int tvWidthPixelsLabel = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int tvWidthPixelsValue = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int tvXdpiLabel = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int tvXdpiValue = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int tvYdpiLabel = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int tvYdpiValue = 2131230741;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DisplayMetrics = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Preferences = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int Main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int CalculatorActivity = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int CancelLabel = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int DefaultCalcNum1Label = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int DefaultCalcNum2Label = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int DensityDpiLabel = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int DensityLabel = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int DisplayMetricsActivity = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int HeightPixelsLabel = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int PreferencesActivity = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int QuitMenuItem = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int ResetMenuItem = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int SaveLabel = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int ScaledDensityLabel = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int WidthPixelsLabel = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int XdpiLabel = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int YdpiLabel = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int buttonInLandOrientation = 2131099666;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
